apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-juan
  labels:
    app: hola-juan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hola-juan
  template:
    metadata:
      labels:
        app: hola-juan
    spec:
      containers:
        - name: hola-juan
          image: docker.io/jcastro14/hola-juan:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 15
